controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    manipulator_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ur5_controller:
      type: position_controllers/JointGroupPositionController

# parameters for each controller listed under controller manager
manipulator_joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - elbow_joint
      - shoulder_lift_joint
      - shoulder_pan_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true # was false by default
    open_loop_control: true 
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0

ur5_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    write_op_modes:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint